
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


sensor bme280:
  - platform: mqtt
    state_topic: "weather/bme280/temperature"
    name: "Temperature Sensor BME280"
    unit_of_measurement: "°C"
    unique_id: "bme280_temperature"
    state_class: measurement
    device_class: temperature
  - platform: mqtt
    state_topic: "weather/bme280/humidity"
    name: "Humidity Sensor BME280"
    unit_of_measurement: "%"
    unique_id: "bme280_humidity"
    state_class: measurement
    device_class: humidity
  - platform: mqtt
    state_topic: "weather/bme280/pressure"
    name: "Pressure Sensor BME280"
    unit_of_measurement: "hPa"
    unique_id: "bme280_pressure"
    state_class: measurement
    device_class: pressure


sensor winddir:
  - platform: mqtt
    state_topic: "weather/winddirection/winddir"
    name: "Wind Direction"
    unit_of_measurement: "Compass Heading"
    unique_id: "winddir"
    state_class: measurement


sensor windspeed:
  - platform: mqtt
    state_topic: "weather/windspeed/windspeed"
    name: "Windspeed"
    unit_of_measurement: "km/h"
    unique_id: "windspeed"
    state_class: measurement


sensor rainmeter:
  - platform: mqtt
    state_topic: "weather/rainmeter/rain24h"
    name: "Rain mm per 24 hours"
    unit_of_measurement: "rain in mm per 24 hours"
    unique_id: "rainmeter_24hours"
    state_class: measurement
  - platform: mqtt
    state_topic: "weather/rainmeter/rain1h"
    name: "Rain mm per hour"
    unit_of_measurement: "rain in mm per hour"
    unique_id: "rainmeter_1hour"
    state_class: measurement
  - platform: mqtt
    state_topic: "weather/rainmeter/rainmonth"
    name: "Rain mm per month"
    unit_of_measurement: "rain in mm per month"
    unique_id: "rainmeter_month_copy"
    state_class: measurement


sensor pmsa003:
  - platform: mqtt
    state_topic: "weather/airquality/pm10_cf1"
    name: "PM1.0 standard particle"
    unit_of_measurement: "μ g/m3"
    unique_id: "pm10_cf1"
    state_class: measurement
  - platform: mqtt
    state_topic: "weather/airquality/pm25_cf1"
    name: "PM2.5 standard particle"
    unit_of_measurement: "μ g/m3"
    unique_id: "pm25_cf1"
    state_class: measurement
  - platform: mqtt
    state_topic: "weather/airquality/pm100_cf1"
    name: "PM10.0 standard particle"
    unit_of_measurement: "μ g/m3"
    unique_id: "pm100_cf1"
    state_class: measurement
  - platform: mqtt
    state_topic: "weather/airquality/pm10_std"
    name: "PM1.0 atmospheric environment"
    unit_of_measurement: "μ g/m3"
    unique_id: "pm10_std"
    state_class: measurement
  - platform: mqtt
    state_topic: "weather/airquality/pm25_std"
    name: "PM2.5 atmospheric environment"
    unit_of_measurement: "μ g/m3"
    unique_id: "pm25_std"
    state_class: measurement
  - platform: mqtt
    state_topic: "weather/airquality/pm100_std"
    name: "PM10.0 atmospheric environment"
    unit_of_measurement: "μ g/m3"
    unique_id: "pm100_std"
    state_class: measurement
  - platform: mqtt
    state_topic: "weather/airquality/gr03um"
    name: "particles with diameter beyond 0.3 μm in 0.1 L of air"
    unit_of_measurement: "particle 0.3 μm/0.1L"
    unique_id: "gr03um"
    state_class: measurement
  - platform: mqtt
    state_topic: "weather/airquality/gr05um"
    name: "particles with diameter beyond 0.5 μm in 0.1 L of air"
    unit_of_measurement: "particle 0.5 μm/0.1L"
    unique_id: "gr05um"
    state_class: measurement
  - platform: mqtt
    state_topic: "weather/airquality/gr10um"
    name: "particles with diameter beyond 1 μm in 0.1 L of air"
    unit_of_measurement: "paricle 1.0 μm/0.1L"
    unique_id: "gr10um"
    state_class: measurement
  - platform: mqtt
    state_topic: "weather/airquality/gr25um"
    name: "particles with diameter beyond 2.5 μm in 0.1 L of air"
    unit_of_measurement: "particle 2.5 μm/0.1L"
    unique_id: "gr25um"
    state_class: measurement


sensor geiger:
  - platform: mqtt
    state_topic: "weather/geiger/count"
    name: "Geiger Count"
    unit_of_measurement: "count/min"
    unique_id: "geiger_count"
    state_class: measurement
  - platform: mqtt
    state_topic: "weather/geiger/uSvh"
    name: "Radiation in μSv/h"
    unit_of_measurement: "μSv/h"
    unique_id: "geiger_usvh"
    state_class: measurement


homeassistant:
  customize: !include customize.yaml