version: '3.7'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/portainer_data:/data

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - /docker/mosquitto_config:/mosquitto/config
      - /docker/mosquitto_data:/mosquitto/data
      - /docker/mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      TZ: Europe/Zurich
    #network_mode: host

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/raspberrypi3-homeassistant:stable"
    volumes:
      - /docker/home-assistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
